### ISSUE TITLE
关于 getg 的一些疑问

### ISSUE THREAD

**Issue by Ruomenger** [go-kiss/monkey#16]
目前`monkey`中`getg`函数的实现在windows平台下是
```asm
mov r13,QWORD PTR gs:0x28
mov r12,QWORD PTR [r13]
```
在linux平台下的实现是
```asm
mov r12,QWORD PTR fs:0xfffffffffffffff8
```
我在 https://go.googlesource.com/go/+/refs/heads/dev.regabi/src/cmd/compile/internal-abi.md 和自己的测试中发现go使用r14寄存器
存储当前的goroutine指针，那么为何不能直接获取r14的值来用呢？

![1696777792787](https://github.com/go-kiss/monkey/assets/23385044/e57d6e37-3560-4969-ba26-73243836e77b)

![image](https://github.com/go-kiss/monkey/assets/23385044/5eaa8ef3-7ffe-4357-a9f1-04d5ba68b7a6)

我将`getg`在windows和linux的实现修改为了
```go
func getg() []byte {
	return []byte{
		// mov r12, r14
		0x4D, 0x89, 0xF4,
	}
}
```
都是可以正常跑通测试的，并不会有问题，那么之前的这种写法是有什么别的考虑吗？如果没有的话用这种方法应该可以统一win/linux(应该也包括intel版mac，但是m1芯片的mac是arm应该不行)的`getg`实现，且解决之前的windows平台下panic的问题。

![image](https://github.com/go-kiss/monkey/assets/23385044/22ca42f2-ab3b-4b6d-8501-c54925b18bcc)

@taoso FYI

**Comment by taoso** [comment]
这部分代码我是反汇编 go-tls 代码找到的，还专门写了篇博客记录过程 https://taoshu.in/go/monkey/monkey-2.html

我在第一篇文章中也引用了 internal-abi，但没有注意到 R14 中保存了当前协程。

你这个方案在 macos 下也没问题，我同时测试了 go1.18 和 go1.21，确实优雅 👍 你来提 PR 吧

**Comment by Ruomenger** [comment]
好的
