### ISSUE TITLE
能否恢复 PatchInstanceMethod 函数

### ISSUE THREAD

**Issue by samanhappy** [go-kiss/monkey#19]
项目中使用了 `bou.ke/monkey`，但由于其不再维护需要寻找一个替代方案。

另外，项目代码中大量使用了 `PatchInstanceMethod` 函数，但是这个函数在 [重新支持全局打桩 PR#7](https://github.com/go-kiss/monkey/pull/7) 被移除了。

所以想问，能否恢复 `PatchInstanceMethod` 函数，保持向前兼容，这样其他项目只需要替换引用的包就可以了？

**Comment by taoso** [comment]
@samanhappy 可以恢复 `PatchInstanceMethod` 函数，不过需要你来提 PR 了
