### ISSUE TITLE
是否支持m1

### ISSUE THREAD

**Issue by mustangcoder** [go-kiss/monkey#2]

**Comment by mustangcoder** [comment]
原来的mokey不支持m1,这个支持吗

**Comment by epii1** [comment]
暂不支持～我没有 m1 设备 😭

**Comment by taoso** [comment]
M1 平台不允许动态修改程序的代码段。研究了半天也没找到解决方法。一些类似的项目说是可以支持，但也是通过编译成 x86 程序来实现的，本质上还是不支持。我先关闭这个问题了。
