### ISSUE TITLE
Monkey patch 的中文译名

### ISSUE THREAD

**Issue by FlowBreeze** [go-kiss/monkey#5]
猴子补丁听起来怪怪的
比较官方的叫法应该为[**猴补丁**](https://zh.wikipedia.org/wiki/%E7%8C%B4%E8%A1%A5%E4%B8%81)

**Comment by taoso** [comment]
用谷歌搜索「猴补丁」，结果还是有很多「猴子补丁」。感觉「猴补丁」不太符合现代汉语的使用习惯。
<img width="400" alt="image" src="https://user-images.githubusercontent.com/2030591/161358339-c4d20251-d9e1-4c6c-a8b4-fd3d9d29cf74.png">

**Comment by FlowBreeze** [comment]
好的,没事了
